HW_1 committed 28.11.2018
rogozhinski/html_css_rogozhinski pull request #1
Opened 2018-11-28 19:09 UTC by rogozhinski

Signed-off-by: Konstantin_Rogozhinski <rogozhinskiks@gmail.com>

2018-12-02 11:46 UTC, tanchu requested changes

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    margin-bottom: 30;
не указана размерность. Забыл px

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +form.main {
у всех селекторов убери тэги.
form.main -> .main

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    padding-top: 90px;
есть короткая форма записи padding и  margin
вместо того, чтобы писать 4 правила, можео записать одно
padding: 90px 70px 90px 70px // top right bottom left
padding: 90px 70px;  // но в твоем случае можно еще короче top & bottom  right & left
сделай так везде, пожалуйста

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    color: red;
укажи  цвет hex.  red в различных браузерах может выглядеть по-разному

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    type: "text";
нет такого правила
вероятно ты имел ввиду атрибут type, он указывается у  самого тэга

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    outline: 0 !important;
сделай без important

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    border: 0.5px solid rgba(255,0,0,1);
пиксель - это минимальная единица  графики. 
Не бывает половины от минимальной единицы :) 
поправь  везде.

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    box-shadow: 0 0 5px 0 rgba(255,0,0,1);
ты, видимо, пытался реализовать outline, но не надо так делать
удали это правило

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    width: 608px;
100%

2018-12-02 11:46 UTC, tanchu commented on styles.css
> +    box-shadow: 0 0 5px 0 rgba(255,0,0,1);
обнули outline

2018-12-02 12:46 UTC, rogozhinski commented on styles.css
> +    width: 608px;
Это касается width?

2018-12-02 14:12 UTC, rogozhinski commented on styles.css
> +    box-shadow: 0 0 5px 0 rgba(255,0,0,1);
border-shadow убрал, а вот border на outline поменять все же не решился: в таком случае серая скругленная граница и красный outline при :focus не совпадают, и некрасиво получается.

2018-12-02 14:44 UTC, tanchu requested changes

2018-12-02 14:44 UTC, tanchu commented on styles.css
>      border-radius: 5px;
2px

2018-12-03 11:31 UTC, tanchu commented on styles.css
> +    box-shadow: 0 0 5px 0 rgba(255,0,0,1);
не сделал

2018-12-03 11:32 UTC, tanchu commented on styles.css
>      border-radius: 5px;
не сделал

2018-12-03 11:32 UTC, tanchu commented on styles.css
> +    box-shadow: 0 0 5px 0 rgba(255,0,0,1);
убери outline вообще

2018-12-30 13:39 UTC, closed without merging